### ISSUE TITLE
DirectShape.ByGeometry hates view templates

### ISSUE THREAD

**Issue by andydandy74** [dimven/SpringNodes#13]
`DirectShape.ByGeometry` needs a `view` to perform its operations and it tries to find that `view` by means of a `FilteredElementCollector` and subsequent filtering by `ViewType`. However, if the first suitable `view` it finds is a `ViewTemplate`, the node will throw the following error:
`File "<string>", line 60, in NewDS
Exception: The view is not printable.
Parameter name: pDBView`
I think you will need to use `IsTemplate` as a secondary filter to make sure that doesn't happen.

**Comment by dimven** [comment]
Thanks. I'll add this in the next release.
