### ISSUE TITLE
DirectShape.ByGeometry creates DS, but outputs an error

### ISSUE THREAD

**Issue by andydandy74** [dimven/SpringNodes#14]
As the title says, the object is created, but does not appear in the node output, instead:
`File "<string>", line 88, in NewDS
SystemError: Der Typeninitialisierer für "Revit.Elements.DirectShape" hat eine Ausnahme verursacht.`
This is likely caused by the `ToDSType()` call, since this function only supports a very small portion of all Revit categories/types. (See https://github.com/DynamoDS/Dynamo/issues/2460 for more info...)

**Comment by andydandy74** [comment]
Removing the `ToDSType()` call will result in there not being an error message. Instead, the node returns `null`. It would be really nice if it could return the newly created element for downstream use...

**Comment by dimven** [comment]
I've never had this problem before. Do you mind sharing an example where this happens?

**Comment by andydandy74** [comment]
This happened when converting a geometrically complex shared family nested into another. I'll see if I can create a minimal reproducible test case next week.

**Comment by dimven** [comment]
The node has gone through a few revisions since. Give it another go and post here if you see this happening again. Closing for now.
