### ISSUE TITLE
Mesh.ToPolySurface crashes Revit if Mesh is too simple

### ISSUE THREAD

**Issue by andydandy74** [dimven/SpringNodes#20]
Feeding a very simple mesh (in this case just four points) into Mesh.ToPolySurface will consistently crash Revit 2016 and 2017. Increasing the number of points will solve the issue so it's no big deal, but still interesting, I think.
[SuperSimpleTopo.zip](https://github.com/dimven/SpringNodes/files/597246/SuperSimpleTopo.zip)

**Comment by dimven** [comment]
Thanks for catching this one. I hadn't considered this possibility.  I'll implement a check.

**Comment by dimven** [comment]
This should be fixed in the latest 110.0.2 release.
