### ISSUE TITLE
Wish: Include option to change ToDSType() to True

### ISSUE THREAD

**Issue by josols** [dimven/SpringNodes#21]
@dimven Wish for the FamilyInstance.ByGeometry node to have an additional input for setting the ToDSType to True. I saw here: [https://forum.dynamobim.com/t/circumvent-revit-object-replacement/7459/9](url) that we can use this to circumvent the element binding and create  familyinstances from multiple runs without deleting the previous. In some cases users find this way of working suitable and most effective.

**Comment by dimven** [comment]
Could you provide an example workflow, where this would be useful ?

**Comment by josols** [comment]
in some cases users find it easier to work like this: 1. Select faces, elements, edges etc etc. 2.Create some new geometry 3. name it 4.create family instance, 5. start over and repeat

**Comment by dimven** [comment]
From my experience, that option is very likely to introduce instability in the dynamo graph (duplicate elements being created on top of each other in a single run, dynamo crashing or freezing). Have you experienced something similar?

Closing the graph, without saving it, and then reopening and re-running it again to create new elements, is much more reliable.

edit: If a power user would like to circumvent that, they can always make a new copy of the node and override the setting.
