### ISSUE TITLE
Springs.List.MergeByBoolMask

### ISSUE THREAD

**Issue by Curty102** [dimven/SpringNodes#22]
Dimitar,

I just discovered this node after rereading your response to my nullhandling request on GitHub for Dynamo (https://github.com/DynamoDS/Dynamo/issues/6846).  It is brilliant, interfaces fairly well with the native List.FilterByBoolMask, and effectively bypasses the need to insert nulls as placeholders.  I do have a couple (very minor) suggestions for improvement:

1. Since most users work Left to Right and Top down, could you relocate the mask input to the bottom of the node?
2. Could you rename the "trueList" and "falseList" to "in" and "out" respectively to better correspond with List.FilterByBoolMask?

Again, great work.

![list_replacenonsequential](https://cloud.githubusercontent.com/assets/13457861/21300786/bf26d6ec-c56c-11e6-97b6-420241a95217.jpg)

**Comment by dimven** [comment]
Sounds good.
