### ISSUE TITLE
Springs.List.GetEvenOdd

### ISSUE THREAD

**Issue by Curty102** [dimven/SpringNodes#23]
Dimitar,

This node seems to be flipped.  See attached:

![springs list getevenodd](https://cloud.githubusercontent.com/assets/13457861/21300920/0d69865a-c56e-11e6-9c1e-9b5565c41b47.JPG)

**Comment by dimven** [comment]
Thanks, I'll change it the next time around. Seems like I switched them around when I merged the two nodes
