### ISSUE TITLE
Springs.Sheet.Views+ Schedule from ScheduleSheetInstance

### ISSUE THREAD

**Issue by ekkonap** [dimven/SpringNodes#24]
Hi Dimitar,
Springs.Sheet.Views+ returns Views and ScheduleSheetInstances. Is that a bug or a feature? 

I corrected for it with a snippet from Sheet.Schedules from Clockwork, in a separate node.

# Forked from Clockwork, Andreas Dieckmann
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

viewports = UnwrapElement(IN[0])
viewlist = list()
for viewport in viewports:
    viewlist.append(viewport.Document.GetElement(viewport.ScheduleId))
OUT = viewlist

**Comment by dimven** [comment]
I think that at the time I needed the schedule instances, so that I could copy them between sheets. It seems it would be preferable if we have a node that also fetches the viewschedule of a sheet instance?

**Comment by ekkonap** [comment]
The route that I ended up taking was a python node to get viewports and schedulesheetinstances, and two seperate python nodes to get the views and schedules. All rolled into one custom node, seems to be working consistently, but not tested against different Revit or Dynamo versions, and not a thought spared for optimizing performance. Any thoughts on that?
