### ISSUE TITLE
FamilyInstance.ByGeometry fails on SAT import

### ISSUE THREAD

**Issue by andydandy74** [dimven/SpringNodes#28]
In some cases, the node will fail to import the geometry. I am not sure if there's anything you can do about it since it may be a Revit issue, but the geometry does import without errors via the OOTB ImportInstance.ByGeometry node. 

Steps to reproduce:
- Change file type of attachment to *.dyn
- Open Advanced Architectural Model that ships with Revit
- Run attached graph

[FamilyInstanceByGeometry___GeometryErrors.txt](https://github.com/dimven/SpringNodes/files/858281/FamilyInstanceByGeometry___GeometryErrors.txt)

**Comment by dimven** [comment]
the name of those rooms end up having illegal characters and that's throwing off the export to sat node:
![revit_2017-03-24_16-41-19](https://cloud.githubusercontent.com/assets/7148394/24286571/bfa99c28-10b0-11e7-8ed1-ccc55cdb8d6a.png)

the built-in node is naming the sats after a randomly generated guid and doesn't experience this. This will also be an issue when writing the family file to disk. It might be wiser to raise an exception and inform the user that a name contains an invalid character and let them sort this out.

**Comment by andydandy74** [comment]
:-)
Should have looked at the room names... 
So it might make sense to replace any of these characters with an underscore:
/ ? < > \ : * | " ^
BTW: Seems like the fastest way to do this is to chain the string.replace commands (see second answer):
http://stackoverflow.com/questions/3411771/multiple-character-replace-with-python

**Comment by dimven** [comment]
I'll leave it to the user to decide how he wants to approach the naming. For now, I've added an early check at the start of the function:

![revit_2017-03-24_17-04-26](https://cloud.githubusercontent.com/assets/7148394/24287310/22b00f98-10b4-11e7-8d19-5a93fb310155.png)

>invalid_chars = System.IO.Path.GetInvalidFileNameChars()
>...
>if any( (c in name1 for c in invalid_chars) ):
>  raise Exception('Family name contains invalid characters')
