### ISSUE TITLE
Springs.CurveLoop.Simplify

### ISSUE THREAD

**Issue by ParametricMonkey** [dimven/SpringNodes#29]
Hi Dimitar

I've been using this node for a while and it always worked perfectly. Now I am running it on Revit 2018 and Dynamo 1.3.1 and the node is failing. There is no error message and my coding isn't good enough to pin point the issue. However, I'm wondering if the issue is due to the new 'geometry working range' setting in Dynamo and the precision.

Thanks

**Comment by dimven** [comment]
I don't think anything on the Revit side will affect it - it's using only Dynamo entities. I last remember using it in 1.21, so it could be some minor change around the geometry in 1.3/ 1.31. I'll have a look this weekend.

**Comment by dimven** [comment]
@ParametricMonkey 
1) does the below work for you:
![image](https://user-images.githubusercontent.com/7148394/28953311-bda18b86-7909-11e7-86f4-4ee325973f84.png)

2) and if not, what packages do you have installed

**Comment by ParametricMonkey** [comment]
@dimven. No, neither work for me.

![1](https://user-images.githubusercontent.com/10913639/28954974-24f3c774-7926-11e7-89f5-3142a559c5dd.png)

Here are the installed packages

![2](https://user-images.githubusercontent.com/10913639/28954975-2854a960-7926-11e7-99f2-e6ae13acd5c2.png)

**Comment by dimven** [comment]
@ksobon's archi-lab has a List class that is causing this:

https://github.com/ksobon/archilab_Grimshaw/blob/master/archilabTypes.cs/List/List.cs

As a quick fix, you'll need to prefix each "List" usage with "DSCore."

![image](https://user-images.githubusercontent.com/7148394/28968758-283197c6-7954-11e7-897a-bf53bbffad4f.png)

EDIT: Scratch that, namespaces are broken in imperative code ... :(

**Comment by dimven** [comment]
This seems to be a known issue that can't be resolved at this time:
https://github.com/DynamoDS/Dynamo/issues/7697

I'm in the process of fixing all namespace clashes and removing all references to the list class in all imperative blocks. I should have a new version out soon.

**Comment by dimven** [comment]
Could you give with ver. 121.0.2 ?

**Comment by ParametricMonkey** [comment]
thanks @dimven. That seems to have worked.
