### ISSUE TITLE
Springs.DirectShape.ByGeometry - Traceback error

### ISSUE THREAD

**Issue by ParametricMonkey** [dimven/SpringNodes#30]
Hi Dimitar

I am trying to use your 'Springs.DirectShape.ByGeometry' node as I don't want any traingulations in the geometry. However I can't seem to get it working. I'm using Revit 2018.1, Dynamo 1.3.1 and Springs 121.0.2.  The python node is returning an error 'Warning: IonPythonEvaluator.EvaluateIronPythonScript operation failed. Traceback (most recent call last):   File "<string>", line 14, in <module>ImportError: No module named traceback

I tried the BrepShape node as well but got the same error message. I've simplified my script to troubleshoot it. It is just one solid and I am feeding in a name. It works with the OOTB node. Any ideas as to why this might be happening?

Thanks

**Comment by dimven** [comment]
Hi Paul,

Based on the error, it seems that Dynamo can't locate the standard iron python library. The lines where the error occurs,  attempt to do just that:

```
pf_path = System.Environment.GetFolderPath(System.Environment.SpecialFolder.ProgramFilesX86)
import sys
sys.path.append("%s\IronPython 2.7\Lib" %pf_path)
import traceback #This is line 14, where the error is generated from
```

Could you check and verify that you have iron python installed at: 

> C:\Program Files (x86)\IronPython 2.7

 or whichever drive your windows install is at

I can't see any other issue on my end:

![image](https://user-images.githubusercontent.com/7148394/29199143-ea3b2f44-7e7c-11e7-85bb-e78bece87d3f.png)

**Comment by ParametricMonkey** [comment]
Mine seems to be saved here:

![image](https://user-images.githubusercontent.com/10913639/29201034-e47baf04-7e9d-11e7-89a3-1a0025e460b5.png)

**Comment by dimven** [comment]
We actually need the library folder. It should look something like this:

![image](https://user-images.githubusercontent.com/7148394/29201061-7ce8be00-7e8d-11e7-9f6c-912548e44e6a.png)

Dynamo will usually install that automatically

**Comment by ParametricMonkey** [comment]
interesting. Is IronPython installed with other software - like Revit or Dynamo? Or is it standalone and I need to install it separately. How sure how it got installed on my work pc.

**Comment by ParametricMonkey** [comment]
It is actually installed here:
![image](https://user-images.githubusercontent.com/10913639/29202169-b56c614e-7ea8-11e7-90f4-f3cd0d497ef2.png)

**Comment by dimven** [comment]
Yeah, that doesn't look right. If no previous install is found, IronPython 2.7.3 should be installed silently with every version of Dynamo inside your 32bit program files folder. Are you using some kind of a custom deployment? It might be installing this python incorrectly.

**Comment by ParametricMonkey** [comment]
yes its deployed over citrix. I'll case up with the IT guys to see why. Is the Springs package looking for that particular library location? Any way to set an alternative location?

**Comment by dimven** [comment]
You can always edit the python script and add a custom location like so:
> sys.path.append(##custom path as a string##) 

alternatively, you can remove the references to the traceback module. It's only there to provide a more detailed exception message.

**Comment by ParametricMonkey** [comment]
Hi Dimitar. Just a quick update - I finally got around to this. I moved the location of ironPython as you suggested and it fixed the problem. I needed to do this as it was also causing problems with Ladybug +. We tracked down the installation to that folder to Dynamo 0.8. Maybe we didn't uninstall before installing the later versions. Anyway, thanks for your help!

**Comment by dimven** [comment]
Glad it worked out
