### ISSUE TITLE
Wish: Create single PolySurface from nested list of Meshes

### ISSUE THREAD

**Issue by andydandy74** [dimven/SpringNodes#33]
Hi Dimitar,
it would be nice if Springs.Mesh.ToPolySurface could stitch multiple meshes into a single polysurface, like so:
![grafik](https://user-images.githubusercontent.com/3014437/31179249-bbf209e0-a91b-11e7-951f-8fb2e0d4adc7.png)
(or perhaps with a boolean input "UnionAll")

**Comment by dimven** [comment]
You don't need to extract the surfaces to create a merged polysurface. Therefore this was an easy an quick option :)

![revit_2017-11-05_23-36-48](https://user-images.githubusercontent.com/7148394/32416349-bf200de4-c282-11e7-8b19-894b696b5c34.png)
