### ISSUE TITLE
Springs.Shaft.ByCurves issues

### ISSUE THREAD

**Issue by zachbeale** [dimven/SpringNodes#35]
Hello,

I can't get springs.shaft.BrCurves to work for the life of me. I've tried different configurations of polycurves, both joined and unjoined, and different configurations of levels. Each input has the same list structure, yet all I ever get is a null. Any ideas?

**Comment by dimven** [comment]
Hi,

Have a look at the "Shaft.ByCurves sample.dyn" and the similarly named revit file inside the [samples folder](https://github.com/dimven/SpringNodes/tree/master/Samples)

![image](https://user-images.githubusercontent.com/7148394/32582841-becea6c4-c52b-11e7-97c9-13d6d797d63f.png)

**Comment by zachbeale** [comment]
Thanks for the fast reply. Your sample is working great, but I don't know why the process isn't working on my file. We have a few special conditions, one, the floor intersection information is being pulled form a linked file, though that shouldn't be an issue because the resulting curves work fine, secondly, we have multiple shafts stretching between multiple levels (the whole point of this is to build shafts for mechanical risers. in the included screenshot i'm only processing four ducts to debug), so our lists are a level more complicated than yours. I'm not sure if I'm doing something wrong with the listing, or the node isn't accepting the leveled lists. Am I missing something?
![capture](https://user-images.githubusercontent.com/33494040/32609314-464ff552-c52d-11e7-8cf1-bcdfe361bd1b.JPG)

**Comment by dimven** [comment]
I suspect it's because of your list structure. Try flattening the lists for the base & top levels.

**Comment by zachbeale** [comment]
I isolated just the first respective top and bottom levels, as well as the first shaft only, and I'm still getting an empty. I've attached the script for you to see. It's very possible I'm doing something wrong, but I'm really not sure.
![capture3](https://user-images.githubusercontent.com/33494040/32673739-36258dda-c61e-11e7-832a-a19887bf26ef.JPG)
[risers fam create-openings coord anno 05.txt](https://github.com/dimven/SpringNodes/files/1462397/risers.fam.create-openings.coord.anno.05.txt)

**Comment by dimven** [comment]
Not sure why you're getting an empty list. The node should return a null if it fails. If I recreate your list structure however, I get a shaft as expected:

![image](https://user-images.githubusercontent.com/7148394/32717827-072930d4-c896-11e7-8936-55544c76efdb.png)

Are you on the latest version and if not, could you try updating?
