### ISSUE TITLE
Improvement: Springs.ViewSet.ByViewsName

### ISSUE THREAD

**Issue by DanielHurtubise** [dimven/SpringNodes#39]
Would it be possible to set the .. Set as active after the update?
![image](https://user-images.githubusercontent.com/4299930/35503176-ace24ee0-04df-11e8-9ca4-20f1e44624be.png)

**Comment by dimven** [comment]
There's nothing on this in the api view set class unfortunately. I suspect it's only exposed in the c4r plugin :/
