### ISSUE TITLE
Cannot import .obj mesh to Revit as an instance

### ISSUE THREAD

**Issue by xyang01** [dimven/SpringNodes#40]
Dear Dimitar
I utilized the familyinstance to import the mesh surface to Revit. The geometry can be watched in Dynamo, yet it cannot be loaded in Revit. I have tried “directshape” and “familyinstance” , but both of them cannot work.
Here is my dynamo code, and I really appreciate your help.
![capture](https://user-images.githubusercontent.com/26739163/36795660-e9ae9fe6-1ca3-11e8-98ae-84625ae05d27.png)

**Comment by dimven** [comment]
Hi,

have a look at my reply in the forum: https://forum.dynamobim.com/t/cannot-import-mesh-to-revit-as-instance/19511/10?
