### ISSUE TITLE
Springs.Element.Unjoin

### ISSUE THREAD

**Issue by DanielHurtubise** [dimven/SpringNodes#41]
Morning,
im working on a definition to unjoin elements that generated warnings when not join.
Im not sure why im getting null though
![image](https://user-images.githubusercontent.com/4299930/37022727-268c3b74-2124-11e8-884b-b442acc90d17.png)

**Comment by dimven** [comment]
Hi Daniel,

Archilab's warnings nodes use a custom element object. You'll have to first pull the actual elements from that prior to using them with any of the existing nodes.

**Comment by DanielHurtubise** [comment]
Ahhhh 
I used WarningElement.iD then Select.ByElementId and of course... you we're right :)

Thanks a million
