### ISSUE TITLE
Springs.Collector.ElementSketch

### ISSUE THREAD

**Issue by DanielHurtubise** [dimven/SpringNodes#42]
Morning,
it seems this node won't pull the sketch from a link element am i right?

In my case i'm trying to pull Ceilings sketch but the ceilings are in a link file so i do feed a list of elements but the node returns null
![image](https://user-images.githubusercontent.com/4299930/37087535-deb9f9ee-21fa-11e8-9874-4b5c0d852457.png)

**Comment by dimven** [comment]
Have a look at my reply here - https://forum.dynamobim.com/t/springs-collector-elementsketch-for-linked-elements/17939/4

Getting the sketch element is done with a workaround that's impractical with links. Another option is to get the surface of the floors.
