### ISSUE TITLE
How can we get the french version of revit to work?

### ISSUE THREAD

**Issue by bobbieqc** [dimven/SpringNodes#43]
With spring errorreport.parse in french version of revit

**Comment by dimven** [comment]
Do you mind posting an example error report in french?

**Comment by bobbieqc** [comment]
here it os

2018-03-12 3:03 GMT-04:00 Dimitar Venkov <notifications@github.com>:

**Comment by DanielHurtubise** [comment]
Je crois que tu as oublie l'image :)
I think you forgot the attachement :)

**Comment by bobbieqc** [comment]
Here it is[
[OLIV-BÂTIMENT-A.txt](https://github.com/dimven/SpringNodes/files/1821104/OLIV-BATIMENT-A.txt)

](url)

**Comment by bobbieqc** [comment]
[OLIV-BÂTIMENT-A.txt](https://github.com/dimven/SpringNodes/files/1821105/OLIV-BATIMENT-A.txt)
Et voilla

**Comment by bobbieqc** [comment]
et voila

**Comment by dimven** [comment]
Try a slightly revised version:
[ErrorReport.Parse.zip](https://github.com/dimven/SpringNodes/files/1822659/ErrorReport.Parse.zip)
![revit_2018-03-18_20-49-43](https://user-images.githubusercontent.com/7148394/37566064-0bc13d10-2aef-11e8-8221-c3130d4c9a7b.png)
