### ISSUE TITLE
Springs. Dictionnary returns null when String has a space in it

### ISSUE THREAD

**Issue by DanielHurtubise** [dimven/SpringNodes#46]
Hi Dimitri,
check this out. I f i remove the space the dictionnary works fine.
![image](https://user-images.githubusercontent.com/4299930/41598262-f403af9e-73cf-11e8-8a1c-2b10679a419f.png)

**Comment by dimven** [comment]
My guess is there's trailing spaces in those strings that are getting removed too. Try counting the length of the strings or using the TrimWhitespaces node, that's the best indication.

**Comment by DanielHurtubise** [comment]
RIGHT ON :)
Sorry for bothering you :)
