### ISSUE TITLE
Enhancement: Change the FamilyByGeometry's origin to the origin

### ISSUE THREAD

**Issue by dimven** [dimven/SpringNodes#5]
Right now the form is created at the same coordinates as the host geometry in Dynamo(or the host project). Create the form at the family origin and translate as necessary. This might raise some issues with the host/family units and scale.

**Comment by jamiefarrell** [comment]
I'm in the camp and sometimes enjoy host project origin for one point instantiation, however I feel  if units and scale can be controlled for it would be worth standard family generation also. Could always instantiate using bounding box centroid of referencing geometry.

But that's just my two cents. : )

Jamie

Sent from my iPhone
On Dec 5, 2015, at 12:41 AM, Dimitar Venkov <notifications@github.com<mailto:notifications@github.com>> wrote:

Right now the form is created at the same coordinates as the host geometry in Dynamo(or the host project). Create the form at the family origin and translate as necessary. This might raise some issues with the host/family units and scale.

**Comment by dimven** [comment]
Will be implemented in the next version
