### ISSUE TITLE
Springs.Filter.ByCategoryName also returns Tags

### ISSUE THREAD

**Issue by DavePlumb** [dimven/SpringNodes#51]
The Springs.Filter.ByCategoryName node returns both the Category passed and the Tags associated with that Category. It looks like the filter function acts as a wildcard, not as an exact match
![Springs](https://user-images.githubusercontent.com/18071127/57384275-eb0b2800-7175-11e9-8277-17252f24867c.PNG)

**Comment by dimven** [comment]
Hi,

Yes, that's the intended use. I wanted to keep it more generic, so the node takes a list of strings and checks for partial matches. To get just the rooms, you have two options:

![image](https://user-images.githubusercontent.com/7148394/57684845-48ecb380-763f-11e9-9bb3-3810021af274.png)

Either get just the room*S* or if let's say you want to check if every room has a tag, do one extra step of filtering like in option 2

**Comment by DavePlumb** [comment]
I did not know about the plural. Thanks for the tip!
Does that work with all categories?
Here's what I had done. But now that you mention it, that would not have excluded the RS lines
![image](https://user-images.githubusercontent.com/18071127/57712273-e04d0900-7635-11e9-835d-5249a028abcb.png)
