### ISSUE TITLE
Document.CentralPath

### ISSUE THREAD

**Issue by mrainville1618** [dimven/SpringNodes#52]
noticed in dyn2.0 the Document.CentralPath node fails and is missing the python node within the custom node.
![image](https://user-images.githubusercontent.com/20841797/57709449-e3d59580-761f-11e9-8597-4dc87eb9a280.png)
When I went back into the dyn 1.3.4 version and copied the python code out it comes up with this:
![image](https://user-images.githubusercontent.com/20841797/57709587-30b96c00-7620-11e9-8dac-17848c3620c2.png)

Thank you so very much for making this package, I use this node more than others, but certainly make use of a lot of them.

-Mark

**Comment by dimven** [comment]
Hi, I'm not sure what was the issue but I can't replicate it. Everything behaves as expected:
![image](https://user-images.githubusercontent.com/7148394/64698764-27e08600-d4ac-11e9-8d91-a8223ff7ecb8.png)

**Comment by mrainville1618** [comment]
Thank you. Yes, I am in a new position at a new company, and it does work
in dynamo 2.0.3 in revit 2019, so it might have been an issue with pyrevit
in the old environment.
