### ISSUE TITLE
parse Interferencecheck node 

### ISSUE THREAD

**Issue by Mohamadnawar** [dimven/SpringNodes#54]
Hello,

The below node not working in Revit 2020

![image](https://user-images.githubusercontent.com/51643804/59195952-68272400-8b9e-11e9-900b-3280b5133b6d.png)

**Comment by mehmetduzenli** [comment]
i have the same problem

**Comment by dimven** [comment]
Revit 2020 uses a new version of iron python - 2.7.8. The way this new version opens and reads text files seems to be different. Still trying to figure out why.

**Comment by dimven** [comment]
As a temporary fix, edit the python script and replace  lines 48 to 50 as such:

![image](https://user-images.githubusercontent.com/7148394/59446348-01a63e00-8e0a-11e9-8ad6-3dded137836e.png)
```

with System.IO.File.OpenText(report1) as f:
	while not f.EndOfStream:
		parser.feed(f.ReadLine().replace("&", ""))

```

**Comment by dimven** [comment]
the python equivalent of the above code seems to be:

```
import io
with io.open(filepath, "r", encoding="utf-16") as f:
    for line in f:
        print line
```

**Comment by Mohamadnawar** [comment]
Thank you working perfectly now
