### ISSUE TITLE
Tool.ElementsInGroup not working

### ISSUE THREAD

**Issue by JacobSmall** [dimven/SpringNodes#55]
Found a lacing issue which appears to be a result of list handling in this nodes. The "List.Equals" needs to be changed from Auto lacing to longest to ensure that all items iterate over the list. It might be worth adding cross product to enable lists of lists of target items but the same functionality can be achieved using list levels on the placed version of the custom node so that's likely an unnecessary complication. 

Forum topic which spurred the issue can be found here: https://forum.dynamobim.com/t/tool-elementsingroup-not-working-steamnodes/38866?u=jacobsmall

**Comment by dimven** [comment]
Hi Jacob,

This node is part of Julien Benoit's Steam Nodes package. I'm not sure if he's had the chance to migrate his package to 2.0 but I'll be sure to pass along the issue.
