### ISSUE TITLE
PolyCurve.Byjoined curves not working

### ISSUE THREAD

**Issue by bobbieqc** [dimven/SpringNodes#58]
![image](https://user-images.githubusercontent.com/37275193/74032137-3eb6d600-4981-11ea-9a22-0a1ada369e87.png)

![image](https://user-images.githubusercontent.com/37275193/74032193-5c843b00-4981-11ea-9f6e-2cdb0314a71d.png)

Have problem in dynamo 1.3 as well as 2...any idea

**Comment by dimven** [comment]
That's a dynamo issue :/
Try changing your units scale from the dynamo settings
