### ISSUE TITLE
FamilyInstance.ByGeometry-Wall by Face-Attach or Detach Top/Base

### ISSUE THREAD

**Issue by mustafateksoy** [dimven/SpringNodes#61]
Hello,
Thank you for the great tool-set.
I made a wall using Wall by Face, after creating Generic Model with FamilyInstance.ByGeometry node. However it is not possible to attach or detach top/base of the wall. Is there a way to do it ?

**Comment by dimven** [comment]
no, this is a Revit limitation. Walls can only be attached to system components like floors and roofs
