### ISSUE TITLE
/W Parse.InterferenceCheck

### ISSUE THREAD

**Issue by aumaco** [dimven/SpringNodes#62]
Using the Dynamo version Revit 2.3.0.8352 and Core 2.3.0.58.85 I got null on all outputs.

![node](https://user-images.githubusercontent.com/22150163/113349789-f558e100-930e-11eb-85b3-2c802cdb58e8.png)

Unziping the node I got this

![error](https://user-images.githubusercontent.com/22150163/113349746-e2461100-930e-11eb-884c-4d45293b9f1b.png)

Same on version 2.1.0.XXXX

**Comment by dimven** [comment]
Around v 2.3 the ironpython engine was updated and changed the way files are read when using the native python file reader. The best solution I've found is to completely avoid it and use the C# System.IO methods.
As a quick fix, you'll need to change the following lines:

![image](https://user-images.githubusercontent.com/7148394/113935812-a5db4f00-97ff-11eb-8c5e-bd343f3a3c18.png)

```
with System.IO.File.OpenText(report1) as f:
	while not f.EndOfStream:
		parser.feed(f.ReadLine().replace("&", ""))
```

I'll be sure to include these fixes in the next release.

![image](https://user-images.githubusercontent.com/7148394/113935977-de7b2880-97ff-11eb-9c5b-7974683ee6ad.png)
