### ISSUE TITLE
Document.ActiveView doesn't refresh

### ISSUE THREAD

**Issue by tktechie** [dimven/SpringNodes#63]
Using v204.1.0 from package manager in Revit-2021 & built-in Dynamo 2.6.1.8786/8850

node Document.ActiveView does not appear to refresh, as it's `refresh` input would imply is possible. If I run the same dynamo graph on a new view in Revit, the node keeps the same output: the first view the node ran on, even when there's a Bool-true hard-lined into the node input.

Deleting and recreating the node allows for a single view to be used before having to delete and re-run again. But, to me at least, this node should _refresh_ and grab whatever the current view is every time the script/graph is run.

![Annotation 2021-04-14 130016](https://user-images.githubusercontent.com/7366385/114749799-4e6a4100-9d21-11eb-9fb5-4fd9ba63d95e.png)

**Comment by dimven** [comment]
unfortunately, that's not the intended purpose of the input. The idea is that every time you change the input (manually switch between true/false), the output would change.
